Implement DarkMode
gastsail/expenses-KMP pull request #4
Opened 2023-09-08 01:27 UTC by LucasGinard

# DarkMode 🌙
Buenas Gastón implemente el modo oscuro en ambas plataformas de la mejor forma que pude aguardo feedback.

⚠️ Problema que aun no pude solucionar:
- En iOS cuando la app esta abierta y vas a cambiar tu modo oscuro o a claro no actualiza el modo de la app,
se puede visualizar en el minuto 0:54 (Pero si volves a abrir la app de cero si cambia el tema)

# 🍎iOS

### 🍎 Run

https://github.com/gastsail/expenses-KMP/assets/57275367/1c4bf04a-8a32-43bc-b83c-cf82eda00ded

### 🍎 Screenshots
<div style="display: flex; justify-content: space-between;">
    <img src="https://github.com/gastsail/expenses-KMP/assets/57275367/2d346be2-38ac-4c23-b4fc-959155de85bc" height=400>
    <img src="https://github.com/gastsail/expenses-KMP/assets/57275367/f1557929-d4e2-4b30-8c65-93ca82ad9c5a" height=400>
    <img src="https://github.com/gastsail/expenses-KMP/assets/57275367/ea82d847-84c5-4f38-819a-6a77cfe638cf" height=400>
</div>

# 🤖Android
### 🤖Run

https://github.com/gastsail/expenses-KMP/assets/57275367/8c3bf526-4be9-4f2e-b18b-47b56ccccc8e

### 🤖Screenshots
<div style="display: flex; justify-content: space-between;">
    <img src="https://github.com/gastsail/expenses-KMP/assets/57275367/f9c26ed3-14e6-4653-9a8f-0fd682e843e5" height=400>
    <img src="https://github.com/gastsail/expenses-KMP/assets/57275367/07c4c5dc-99e4-487a-8279-ed60f8b4042b" height=400>
    <img src="https://github.com/gastsail/expenses-KMP/assets/57275367/ab90f5be-499b-4a61-bd4e-2bbab023e4eb" height=400>
</div>

2023-09-08 15:02 UTC, gastsail requested changes
Muchas gracias Lucas por tu PR, muy completo, te dejé alguans dudas para ver si se puede solucionar el tema del dark y light mode en iOS cuando pones la app en segundo plano.

2023-09-08 15:02 UTC, gastsail commented on shared/src/commonMain/kotlin/App.kt
> +    SessionCache.configDevice = configDevice
al salir y volver a entrar a la app con el dark desactivado actualizamos este cache ? o es solo al startup de la app ? , son algunas preguntas para dar con el error de que no se te actualiza al dark mode cuando lo tenes en segundo plano

2023-09-10 19:16 UTC, LucasGinard commented on shared/src/commonMain/kotlin/App.kt
> +    SessionCache.configDevice = configDevice
Buenas estuve probando y no logre obtener cuando vuelve de segundo plano desde el nativo de swift probe con el 
**.onAppear** en la parte de swiftUI y solo me imprimía la primera vez que se abra la app,la otra parte que utiliza UIKit:

```kotlin:
fun mainViewController() = PreComposeApplication { App(CrossConfigDevice()) } 
```

El PreComposeApplication  no es posible acceder a su viewWillAppear que seria igual al onResumen en android.

podría ser que todavía no se logra fixear de la Alpha ? en iOS por ello no entra en el **.onAppear** en los de swiftUI solo cuando se abre la primera vez ?

2023-09-10 19:22 UTC, LucasGinard commented on androidApp/src/androidMain/kotlin/com/myapplication/MainActivity.kt
> +            darkIcons = !isDarkMode
en android si funciona el cambio de color, el onResumen del android podría afectar al de iOS ?

2023-09-10 19:44 UTC, gastsail commented on androidApp/src/androidMain/kotlin/com/myapplication/MainActivity.kt
> +            darkIcons = !isDarkMode
Mala mía , no, no va a funcionar en iOS , solo en Android

2023-09-10 20:22 UTC, LucasGinard commented
# Buenas Gastón 
ya funciona el cambio de tema al volver de segundo plano en iOS:

### 🍎 Run - Corriendo:

https://github.com/gastsail/expenses-KMP/assets/57275367/ce7a9b4b-bc41-44a1-b27d-af2b10b1a4f4

2023-09-10 22:23 UTC, gastsail commented
Excelente el cambio Lucas ! Parece que el onChange validando el cambio de escena solucionó el problema , cuando esté en la computadora me muevo al branch, lo pruebo y lo metemos , gracias por colaborar 🙌

2023-09-11 13:09 UTC, merged